// src/routes/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import {
		ArrowRight,
		ArrowUpRight,
		BadgeCheck,
		Flame,
		RotateCcw,
		Truck,
		ChevronRight,
		Star
	} from '@lucide/svelte';
	import ProductCard from '$lib/components/ProductCard.svelte';
	import { categories, discountPct, formatINR, type Product } from '$lib/catalog';

	let { data }: { data: { products: Product[] } } = $props();

	let products = $derived(data.products);
	let deals = $derived(
		[...products]
			.sort((a, b) => discountPct(b) - discountPct(a) || b.reviews - a.reviews)
			.slice(0, 6)
	);
	let bestSellers = $derived(
		[...products].sort((a, b) => b.rating - a.rating).slice(0, 8)
	);
	let featuredCategories = $derived(
		categories.filter((category) =>
			['ssd', 'ram', 'batteries', 'displays', 'chargers', 'processors'].includes(category.slug)
		)
	);
	let categoryTiles = $derived(
		featuredCategories
			.map((category) => ({
				...category,
				product: products.find((product) => product.category === category.slug)
			}))
			.filter((category) => category.product)
	);

	const serviceNotes = [
		{
			id: 'genuine',
			title: 'Genuine parts',
			body: 'Warranty, compatibility, and grade visible before checkout.',
			icon: BadgeCheck
		},
		{
			id: 'dispatch',
			title: 'Fast dispatch',
			body: 'In-stock parts ship same day from local inventory.',
			icon: Truck
		},
		{
			id: 'returns',
			title: 'Easy returns',
			body: 'DOA replacements and clear return windows on every order.',
			icon: RotateCcw
		}
	];
</script>

<svelte:head>
	<title>LapKart - Premium Laptop Parts</title>
	<meta
		name="description"
		content="Shop laptop SSDs, RAM, batteries, displays, chargers, processors, and repair parts."
	/>
</svelte:head>

<!-- Hero -->
<section class="relative overflow-hidden border-b border-[var(--border-faint)] bg-[var(--accent-black)]">
	<div class="grid-pattern absolute inset-0 opacity-40"></div>
	<div class="container relative mx-auto px-4 py-10 sm:py-20">
		<div class="max-w-xl">
			<p class="text-mono-x-small mb-3 tracking-[0.2em] text-[var(--heat-100)] uppercase sm:mb-4">
				Laptop parts catalog
			</p>
			<h1 class="text-[28px] font-medium leading-[1.15] tracking-tight text-white sm:text-title-h2">
				Upgrade. Repair.<br />
				<span class="gradient-text">Ship fast.</span>
			</h1>
			<p class="mt-3 max-w-md text-[14px] leading-relaxed text-white/60 sm:mt-5 sm:text-body-large">
				SSDs, RAM, batteries, displays, and more — with fitment guidance and same-day dispatch.
			</p>
			<div class="mt-5 flex flex-wrap gap-3 sm:mt-8">
				<a
					href={resolve('/products')}
					class="button button-primary text-label-medium inline-flex h-10 items-center gap-2 rounded-md px-5 sm:h-12 sm:px-6"
				>
					Browse catalog
					<ArrowRight class="size-4" />
				</a>
			</div>
		</div>
	</div>
</section>

<!-- Category quick-nav pills -->
<div class="border-b border-[var(--border-faint)] bg-white">
	<div class="container mx-auto px-4">
		<div class="scrollbar-hide -mx-4 flex snap-x snap-mandatory gap-0 overflow-x-auto px-4 sm:mx-0 sm:gap-1 sm:px-0">
			{#each featuredCategories as cat (cat.slug)}
				<a
					href={resolve(`/products?category=${cat.slug}`)}
					class="motion-soft-link flex snap-start items-center gap-1.5 whitespace-nowrap border-b-2 border-transparent px-3 py-3 text-[12px] font-medium text-[var(--black-alpha-56)] transition-colors hover:border-[var(--heat-100)] hover:text-[var(--heat-100)] sm:px-4 sm:py-4 sm:text-[13px]"
				>
					{cat.name}
				</a>
			{/each}
			<a
				href={resolve('/products')}
				class="motion-soft-link flex snap-start items-center gap-1 whitespace-nowrap border-b-2 border-transparent px-3 py-3 text-[12px] font-medium text-[var(--heat-100)] transition-colors hover:border-[var(--heat-100)] sm:px-4 sm:py-4 sm:text-[13px]"
			>
				View all <ChevronRight class="size-3" />
			</a>
		</div>
	</div>
</div>

<div class="container mx-auto space-y-8 px-4 py-6 sm:space-y-14 sm:py-12">

	<!-- Deals -->
	<section aria-labelledby="deals-heading">
		<div class="mb-3 flex items-center justify-between sm:mb-5">
			<h2 id="deals-heading" class="text-title-h5 flex items-center gap-2 text-foreground sm:text-title-h4">
				<Flame class="size-5 text-[var(--heat-100)]" />
				Today's deals
			</h2>
			<a
				href={resolve('/products')}
				class="text-label-small flex items-center gap-1 text-[var(--heat-100)] transition-colors hover:text-[var(--heat-200)]"
			>
				See all <ChevronRight class="size-3.5" />
			</a>
		</div>

		<div class="scrollbar-hide -mx-4 flex snap-x snap-mandatory gap-3 overflow-x-auto px-4 pb-2 sm:mx-0 sm:gap-4 sm:px-0">
			{#each deals as deal (deal.id)}
				<a
					href={resolve(`/product/${deal.id}`)}
					class="motion-card group block w-[160px] shrink-0 snap-start overflow-hidden rounded-lg border border-[var(--border-muted)] bg-white sm:w-[220px] sm:rounded-xl"
				>
					<div class="relative aspect-[4/3] overflow-hidden bg-[var(--background-lighter)]">
						<span class="absolute top-2 left-2 z-10 rounded-sm bg-[var(--heat-100)] px-1.5 py-0.5 text-[10px] font-semibold text-white sm:text-[11px]">
							-{discountPct(deal)}%
						</span>
						<img
							src={deal.images?.[0] ?? deal.image}
							alt={deal.title}
							class="motion-image size-full object-contain p-3 sm:p-5"
							loading="lazy"
						/>
					</div>
					<div class="p-2.5 sm:p-4">
						<p class="text-mono-x-small truncate tracking-[0.14em] text-[var(--black-alpha-48)] uppercase" style="font-size: 9px">
							{deal.brand}
						</p>
						<h3 class="mt-0.5 line-clamp-1 text-[12px] font-medium leading-tight text-foreground sm:text-[14px]">
							{deal.title}
						</h3>
						<div class="mt-1.5 flex items-baseline gap-1.5 sm:mt-2">
							<span class="text-[13px] font-medium text-[var(--heat-100)] sm:text-[16px]">{formatINR(deal.price)}</span>
							<span class="text-[10px] text-[var(--black-alpha-40)] line-through sm:text-[12px]">{formatINR(deal.mrp)}</span>
						</div>
					</div>
				</a>
			{/each}
		</div>
	</section>

	<!-- Shop by component -->
	<section aria-labelledby="category-heading">
		<h2 id="category-heading" class="text-title-h5 mb-3 text-foreground sm:mb-5 sm:text-title-h4">
			Shop by component
		</h2>

		<div class="grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-4">
			{#each categoryTiles as category, i (category.slug)}
				<a
					href={resolve(`/products?category=${category.slug}`)}
					class="motion-card group relative flex flex-col overflow-hidden rounded-lg border border-[var(--border-muted)] bg-white p-3 sm:rounded-xl sm:p-5
					{i === 0 ? 'col-span-2 sm:col-span-2' : ''}"
				>
					<div class="relative z-10">
						<h3 class="text-[13px] font-medium text-foreground sm:text-[16px] {i === 0 ? 'sm:text-[20px]' : ''}">
							{category.name}
						</h3>
						<span class="mt-1 inline-flex items-center gap-0.5 text-[11px] text-[var(--heat-100)] sm:text-[13px]">
							Browse <ArrowRight class="size-3" />
						</span>
					</div>
					<div class="absolute right-1 bottom-1 {i === 0 ? 'h-[80px] w-[120px] sm:h-[120px] sm:w-[180px]' : 'h-[56px] w-[56px] sm:h-[80px] sm:w-[80px]'} opacity-60 transition-transform duration-500 group-hover:scale-105">
						<img
							src={category.product?.images?.[0] ?? category.product?.image}
							alt={category.name}
							class="size-full object-contain"
							loading="lazy"
						/>
					</div>
				</a>
			{/each}
		</div>
	</section>

	<!-- Best sellers -->
	<section aria-labelledby="best-sellers-heading">
		<div class="mb-3 flex items-center justify-between sm:mb-5">
			<h2 id="best-sellers-heading" class="text-title-h5 text-foreground sm:text-title-h4">
				Best sellers
			</h2>
		</div>

		<div class="grid grid-cols-2 gap-2 sm:grid-cols-3 sm:gap-4 lg:grid-cols-4">
			{#each bestSellers as product (product.id)}
				<div class="animate-fade-up" style:animation-delay={`${Math.min(bestSellers.indexOf(product) * 40, 300)}ms`}>
					<ProductCard {product} />
				</div>
			{/each}
		</div>
	</section>

	<!-- Trust strip -->
	<section class="grain relative overflow-hidden rounded-xl bg-[var(--accent-black)] p-5 sm:rounded-2xl sm:p-10">
		<div class="relative z-10 grid gap-6 sm:grid-cols-3 sm:gap-8">
			{#each serviceNotes as note}
				{@const Icon = note.icon}
				<div class="flex items-start gap-3 sm:flex-col sm:gap-4">
					<div class="grid size-9 shrink-0 place-items-center rounded-full bg-[var(--heat-100)]/12 sm:size-10">
						<Icon class="size-4 text-[var(--heat-100)] sm:size-5" />
					</div>
					<div>
						<h3 class="text-[14px] font-medium text-white sm:text-[16px]">{note.title}</h3>
						<p class="mt-0.5 text-[12px] leading-relaxed text-white/50 sm:mt-1 sm:text-[14px]">{note.body}</p>
					</div>
				</div>
			{/each}
		</div>
	</section>

</div>

<!-- Bottom spacer for mobile tab bar -->
<div class="h-24 md:hidden"></div>

// src/routes/index.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { ProductCard } from "@/components/ProductCard";
import { categories, products } from "@/lib/catalog";
import { Truck, ShieldCheck, RotateCcw, Headphones, ArrowRight, Zap } from "lucide-react";
import hero from "@/assets/hero.jpg";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "LapKart — Genuine Laptop Components & Repair Parts" },
      {
        name: "description",
        content:
          "Shop genuine laptop RAM, SSDs, batteries, displays, motherboards, chargers and repair parts at the best prices. Fast delivery across India.",
      },
      { property: "og:title", content: "LapKart — Genuine Laptop Components" },
      {
        property: "og:description",
        content: "India's marketplace for laptop spare parts. Genuine. Tested. Delivered fast.",
      },
    ],
  }),
  component: Home,
});

function Home() {
  const featured = products.slice(0, 6);
  const trending = products.slice(6, 12);

  return (
    <div className="min-h-screen bg-background">
      <Header />

      {/* Hero */}
      <section className="relative overflow-hidden bg-[var(--gradient-hero)] text-white">
        <div className="container mx-auto grid items-center gap-8 px-4 py-10 md:grid-cols-2 md:py-16">
          <div className="space-y-5">
            <span className="inline-flex items-center gap-1.5 rounded-full bg-saffron px-3 py-1 text-xs font-bold text-saffron-foreground">
              <Zap className="size-3.5 fill-current" /> FLASH SALE · UP TO 60% OFF
            </span>
            <h1 className="font-display text-4xl font-bold leading-tight sm:text-5xl md:text-6xl">
              Every part your <br className="hidden sm:block" />
              laptop deserves.
            </h1>
            <p className="max-w-md text-base text-white/85">
              Genuine RAM, SSDs, batteries, displays, processors and 10,000+ repair parts —
              tested, certified, delivered fast.
            </p>
            <div className="flex flex-wrap gap-3 pt-2">
              <Link
                to="/products"
                className="inline-flex items-center gap-2 rounded-sm bg-saffron px-6 py-3 text-sm font-bold text-saffron-foreground shadow-lg transition hover:brightness-105"
              >
                Shop Components <ArrowRight className="size-4" />
              </Link>
              <Link
                to="/products"
                className="inline-flex items-center gap-2 rounded-sm border border-white/30 bg-white/10 px-6 py-3 text-sm font-semibold backdrop-blur transition hover:bg-white/20"
              >
                Browse Categories
              </Link>
            </div>
          </div>
          <div className="relative">
            <img
              src={hero}
              alt="Laptop components floating"
              width={1600}
              height={768}
              className="w-full rounded-xl shadow-[var(--shadow-pop)]"
            />
          </div>
        </div>
      </section>

      {/* Trust strip */}
      <section className="border-b border-border bg-card">
        <div className="container mx-auto grid grid-cols-2 gap-4 px-4 py-5 text-sm md:grid-cols-4">
          {[
            { i: Truck, t: "Fast Delivery", s: "Across India" },
            { i: ShieldCheck, t: "100% Genuine", s: "Brand certified" },
            { i: RotateCcw, t: "Easy Returns", s: "7-day policy" },
            { i: Headphones, t: "Expert Support", s: "Mon–Sat 9–7" },
          ].map(({ i: Icon, t, s }) => (
            <div key={t} className="flex items-center gap-3">
              <div className="grid size-10 place-items-center rounded-full bg-primary/10 text-primary">
                <Icon className="size-5" />
              </div>
              <div>
                <p className="font-semibold">{t}</p>
                <p className="text-xs text-muted-foreground">{s}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Categories */}
      <section className="container mx-auto px-4 py-10">
        <div className="mb-6 flex items-end justify-between">
          <div>
            <h2 className="text-2xl font-bold">Shop by Category</h2>
            <p className="text-sm text-muted-foreground">From RAM to repair kits — all in one place.</p>
          </div>
          <Link to="/products" className="text-sm font-semibold text-primary hover:underline">
            View all →
          </Link>
        </div>
        <div className="grid grid-cols-3 gap-3 sm:grid-cols-5 lg:grid-cols-9">
          {categories.map((c) => (
            <Link
              key={c.slug}
              to="/products"
              search={{ category: c.slug }}
              className="group flex flex-col items-center gap-2 rounded-lg border border-transparent bg-card p-3 text-center transition hover:border-primary/30 hover:shadow-[var(--shadow-card-hover)]"
            >
              <div className="aspect-square w-full overflow-hidden rounded-md bg-white">
                <img
                  src={c.image}
                  alt={c.name}
                  loading="lazy"
                  className="size-full object-contain p-2 transition group-hover:scale-110"
                />
              </div>
              <span className="text-xs font-semibold">{c.name}</span>
            </Link>
          ))}
        </div>
      </section>

      {/* Flash sale banner */}
      <section className="container mx-auto px-4">
        <div className="overflow-hidden rounded-xl bg-[var(--gradient-saffron)] p-6 text-saffron-foreground sm:p-8">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs font-bold uppercase tracking-widest">Limited time</p>
              <h3 className="font-display text-2xl font-bold sm:text-3xl">
                Big Component Days — Min 40% off Storage & RAM
              </h3>
            </div>
            <Link
              to="/products"
              className="rounded-sm bg-foreground px-5 py-2.5 text-sm font-bold text-background"
            >
              Grab Deals
            </Link>
          </div>
        </div>
      </section>

      {/* Featured */}
      <Section title="Featured Products" subtitle="Hand-picked components customers love.">
        <Grid items={featured} />
      </Section>

      {/* Trending */}
      <Section title="Trending Laptop Parts" subtitle="What everyone's buying this week.">
        <Grid items={trending} />
      </Section>

      <Footer />
    </div>
  );
}

function Section({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return (
    <section className="container mx-auto px-4 py-10">
      <div className="mb-5 flex items-end justify-between">
        <div>
          <h2 className="text-2xl font-bold">{title}</h2>
          <p className="text-sm text-muted-foreground">{subtitle}</p>
        </div>
        <Link to="/products" className="text-sm font-semibold text-primary hover:underline">
          See all →
        </Link>
      </div>
      {children}
    </section>
  );
}

function Grid({ items }: { items: typeof products }) {
  return (
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
      {items.map((p) => (
        <ProductCard key={p.id} p={p} />
      ))}
    </div>
  );
}
