// src/components/ProductCard.tsx
import { Link } from "@tanstack/react-router";
import { Star, ArrowUpRight } from "lucide-react";
import { type Product, discountPct, formatINR } from "@/lib/catalog";

export function ProductCard({ p }: { p: Product }) {
  return (
    <Link
      to="/product/$id"
      params={{ id: p.id }}
      aria-label={`${p.title} by ${p.brand}`}
      className="group relative flex flex-col overflow-hidden rounded-lg border border-[var(--border-muted)] bg-white transition-[transform,box-shadow,border-color] duration-300 ease-[cubic-bezier(0.25,0.1,0.25,1)] hover:-translate-y-1 hover:border-[var(--heat-20)] hover:shadow-[0_24px_56px_-24px_var(--heat-40),0_4px_12px_-4px_rgba(0,0,0,0.06)]"
    >
      {/* Heat ribbon for sale */}
      {discountPct(p) >= 30 && (
        <span className="absolute top-3 left-3 z-10 inline-flex items-center gap-1 rounded-sm bg-[var(--heat-100)] px-2 py-0.5 text-mono-x-small font-medium text-white shadow-[0_2px_8px_0_var(--heat-40)] tracking-wide">
          −{discountPct(p)}%
        </span>
      )}

      <div className="relative aspect-square overflow-hidden bg-[var(--background-lighter)]">
        <img
          src={p.images?.[0] ?? p.image}
          alt={p.title}
          loading="lazy"
          width={640}
          height={640}
          className="size-full object-contain p-6 transition-transform duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-[1.06]"
        />
        {/* Inside border overlay */}
        <span className="pointer-events-none absolute inset-0 border-b border-[var(--border-faint)]" />
        <ArrowUpRight className="absolute top-3 right-3 size-4 text-[var(--black-alpha-32)] transition-[transform,color] duration-300 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[var(--heat-100)]" />
      </div>

      <div className="flex flex-1 flex-col gap-1.5 px-4 py-4">
        <p className="text-mono-x-small uppercase tracking-[0.14em] text-[var(--black-alpha-48)]">
          {p.brand}
        </p>
        <h3 className="line-clamp-2 text-label-small text-foreground leading-snug min-h-[40px]">
          {p.title}
        </h3>

        <div className="mt-1 flex items-center gap-2">
          <span className="inline-flex items-center gap-0.5 text-body-small text-foreground">
            <Star className="size-3 fill-[var(--accent-honey)] text-[var(--accent-honey)]" />
            {p.rating.toFixed(1)}
          </span>
          <span className="text-mono-x-small text-[var(--black-alpha-40)]">
            ({p.reviews.toLocaleString("en-IN")})
          </span>
        </div>

        <div className="mt-auto pt-3 flex items-baseline gap-2 border-t border-[var(--border-faint)]">
          <span className="text-label-large font-medium text-foreground">{formatINR(p.price)}</span>
          <span className="text-body-small text-[var(--black-alpha-40)] line-through">
            {formatINR(p.mrp)}
          </span>
        </div>
      </div>
    </Link>
  );
}

// src/lib/components/ProductCard.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { Star } from '@lucide/svelte';
	import type { Product } from '$lib/catalog';
	import { discountPct, formatINR } from '$lib/catalog';

	let { product, eager = false } = $props<{ product: Product; eager?: boolean }>();

	const discount = $derived(discountPct(product));
</script>

<a
	href={resolve(`/product/${product.id}`)}
	aria-label={`${product.title} by ${product.brand}`}
	class="product-card group relative flex w-full flex-col overflow-hidden rounded-lg border border-[var(--border-faint)] bg-white"
>
	{#if discount >= 30}
		<span
			class="absolute top-1.5 left-1.5 z-10 rounded-sm px-1.5 py-0.5 text-[10px] font-semibold tracking-wide text-white sm:top-3 sm:left-3 sm:px-2 sm:text-[11px]"
			style="background:var(--heat-100);box-shadow:0 2px 8px 0 var(--heat-40)"
		>
			-{discount}%
		</span>
	{/if}

	<div class="product-card-media">
		<img
			src={product.images?.[0] ?? product.image}
			alt={product.title}
			width="400"
			height="400"
			class="product-card-image"
			loading={eager ? 'eager' : 'lazy'}
			fetchpriority={eager ? 'high' : 'auto'}
			decoding="async"
		/>
		<span class="pointer-events-none absolute inset-0" style="border-bottom:1px solid var(--border-faint)"></span>
	</div>

	<div class="flex flex-1 flex-col px-2.5 py-2 sm:px-4 sm:py-3">
		<p class="truncate font-mono text-[10px] uppercase tracking-[0.12em] sm:text-[11px]" style="color:var(--black-alpha-48)">
			{product.brand}
		</p>
		<h3 class="mt-0.5 line-clamp-2 text-[12px] font-medium leading-snug sm:text-[13px]" style="color:var(--foreground);min-height:2.6em">
			{product.title}
		</h3>

		<div class="mt-1 flex items-center gap-1 sm:gap-1.5">
			<Star class="size-3 sm:size-3.5" style="fill:var(--accent-honey);color:var(--accent-honey)" />
			<span class="text-[11px] sm:text-[12px]" style="color:var(--foreground)">{product.rating.toFixed(1)}</span>
			<span class="text-[10px] sm:text-[11px]" style="color:var(--black-alpha-40)">({product.reviews.toLocaleString('en-IN')})</span>
		</div>

		<div class="mt-auto flex items-baseline gap-1.5 pt-2 sm:gap-2 sm:pt-3" style="border-top:1px solid var(--border-faint)">
			<span class="text-[13px] font-semibold sm:text-[15px]" style="color:var(--foreground)">{formatINR(product.price)}</span>
			<span class="text-[11px] line-through sm:text-[12px]" style="color:var(--black-alpha-40)">{formatINR(product.mrp)}</span>
		</div>
	</div>
</a>

<style>
	.product-card-media {
		position: relative;
		width: 100%;
		overflow: hidden;
		aspect-ratio: 16 / 9;
		background: var(--background-lighter);
	}

	.product-card-image {
		display: block;
		width: 100%;
		height: 100%;
		object-fit: contain;
		padding: 12px;
	}

	@media (min-width: 640px) {
		.product-card-media {
			aspect-ratio: 1 / 1;
		}

		.product-card-image {
			padding: 20px;
		}
	}

	.product-card {
		transition: border-color 180ms ease, box-shadow 180ms ease, transform 180ms ease;
	}
	.product-card:hover {
		border-color: var(--heat-20);
		box-shadow: 0 4px 16px -4px rgba(0, 0, 0, 0.08);
		transform: translateY(-2px);
	}
</style>
